# Generated by Django 4.0.6 on 2022-07-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charact_showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=255)),
                ('max_speed', models.CharField(max_length=255)),
                ('ammount_of_eng', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
                ('showroom_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('balance', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('showroom_id', models.IntegerField()),
            ],
        ),
    ]
