# Generated by Django 4.0.6 on 2022-07-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('showroom_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buyer', models.IntegerField()),
                ('price', models.IntegerField()),
                ('showroom_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='unique_buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
                ('showroom_id', models.IntegerField()),
            ],
        ),
    ]
