# Generated by Django 4.0.6 on 2022-07-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_cars_history_unique_buyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='buyer',
            field=models.CharField(max_length=255),
        ),
    ]
