# Generated by Django 4.0.6 on 2022-08-01 09:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_alter_history_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='location1',
            field=django_countries.fields.CountryField(default='RU', max_length=2),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
