# Generated by Django 4.0.6 on 2022-08-01 10:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0005_buyer_buyer_history_listofcars_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom',
            name='location1',
        ),
        migrations.AlterField(
            model_name='showroom',
            name='location',
            field=django_countries.fields.CountryField(default='RU', max_length=100),
        ),
    ]
