# Generated by Django 4.0.6 on 2022-08-01 10:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0006_remove_showroom_location1_alter_showroom_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='location1',
            field=django_countries.fields.CountryField(default='RU', max_length=100),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
