# Generated by Django 4.0.6 on 2022-08-01 11:57

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0008_remove_showroom_location1_alter_showroom_location'),
    ]
    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='location',
            field=django_countries.fields.CountryField(default='RU', max_length=10),
        ),
    ]
