# Generated by Django 4.0.6 on 2022-08-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0010_delete_buyer_delete_buyer_history_delete_listofcars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='ammount_of_eng',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='max_speed',
        ),
    ]
