# Generated by Django 4.0.6 on 2022-08-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0011_remove_cars_ammount_of_eng_remove_cars_engine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='ammount_of_eng',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='engine_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='max_speed',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
