# Generated by Django 4.0.6 on 2022-08-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0012_cars_ammount_of_eng_cars_engine_type_cars_max_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='ammount_of_cars',
            field=models.IntegerField(null=True),
        ),
    ]
