# Generated by Django 4.0.5 on 2022-08-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0013_cars_ammount_of_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='unique_buyers',
            name='amount_of_purchase',
            field=models.IntegerField(null=True),
        ),
    ]
