# Generated by Django 4.0.5 on 2022-08-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_remove_buyer_buyerid_remove_buyer_history_buyerid_and_more'),
        ('showroom', '0014_unique_buyers_amount_of_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='showroom_id',
        ),
        migrations.RemoveField(
            model_name='charact_showroom',
            name='showroom_id',
        ),
        migrations.RemoveField(
            model_name='history',
            name='showroom_id',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='showroom_id',
        ),
        migrations.RemoveField(
            model_name='unique_buyers',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='unique_buyers',
            name='showroom_id',
        ),
        migrations.AddField(
            model_name='cars',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom'),
        ),
        migrations.AddField(
            model_name='charact_showroom',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom'),
        ),
        migrations.AddField(
            model_name='history',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom'),
        ),
        migrations.AddField(
            model_name='unique_buyers',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer'),
        ),
        migrations.AddField(
            model_name='unique_buyers',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom'),
        ),
    ]
