# Generated by Django 4.0.6 on 2022-08-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_rename_buyer_history_buyerhistory'),
        ('showroom', '0016_alter_history_buyer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='charact_showroom',
            new_name='CharactShowroom',
        ),
        migrations.RenameModel(
            old_name='unique_buyers',
            new_name='UniqueBuyers',
        ),
    ]
