# Generated by Django 4.0.5 on 2022-08-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
