# Generated by Django 4.0.5 on 2022-08-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_remove_buyer_buyerid_remove_buyer_history_buyerid_and_more'),
        ('services', '0003_statistics_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='buyerId',
        ),
        migrations.AddField(
            model_name='offers',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer'),
        ),
    ]
