# Generated by Django 4.0.6 on 2022-08-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listOfCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=255, null=True)),
                ('max_speed', models.CharField(max_length=255, null=True)),
                ('ammount_of_eng', models.IntegerField(default=0)),
                ('model', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('providerId', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('ammountOfBuyers', models.IntegerField()),
                ('providerId', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
