# Generated by Django 4.0.5 on 2022-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='providerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('providerId', models.IntegerField()),
                ('showroom_id', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
            ],
        ),
    ]
