# Generated by Django 4.0.6 on 2022-08-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('buyerId', models.CharField(max_length=255)),
                ('balance', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='buyer_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerId', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('showroom_id', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
