# Generated by Django 4.0.6 on 2022-08-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_buyer_last_login_buyer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
    ]
