# Generated by Django 4.0.5 on 2022-08-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0014_unique_buyers_amount_of_purchase'),
        ('buyer', '0005_remove_buyer_last_login_remove_buyer_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyerId',
        ),
        migrations.RemoveField(
            model_name='buyer_history',
            name='buyerId',
        ),
        migrations.RemoveField(
            model_name='buyer_history',
            name='showroom_id',
        ),
        migrations.AddField(
            model_name='buyer_history',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer'),
        ),
        migrations.AddField(
            model_name='buyer_history',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom'),
        ),
    ]
