# Generated by Django 4.0.6 on 2022-08-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0016_alter_history_buyer'),
        ('buyer', '0006_remove_buyer_buyerid_remove_buyer_history_buyerid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buyer_history',
            new_name='BuyerHistory',
        ),
    ]
