# Generated by Django 4.0.5 on 2022-08-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_showroom_id_discount_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='discountOfShowrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('model', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
                ('showroom_id', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('percent', models.IntegerField(null=True)),
            ],
        ),
    ]
