# Generated by Django 4.0.5 on 2022-08-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_remove_listofcars_providerid_and_more'),
        ('showroom', '0015_remove_cars_showroom_id_and_more'),
        ('sales', '0003_discountofshowrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='discountofshowrooms',
            name='showroom_id',
        ),
        migrations.AddField(
            model_name='discount',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
        ),
        migrations.AddField(
            model_name='discountofshowrooms',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom'),
        ),
    ]
